version: '3.8'

services:
  mysql-db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: employees
    ports:
      - "3307:3306"  # Change external port to 3307 to avoid conflicts
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      retries: 5
      start_period: 20s

  flask-app:
    build: ./app
    depends_on:
      mysql-db:
        condition: service_healthy
    ports:
      - "5000:5000"
    environment:
      FLASK_ENV: development

volumes:
  mysql_data:
